name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.29
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Type Check
        run: bun typecheck
      - name: Lint Check
        run: bun lint
      - name: Format Check
        run: bun format
      - name: Test Coverage Check (UI)
        run: bun test:ui
      - name: Test Coverage Check (Server)
        run: bun test:server
